.fixtures.yml, CHANGELOG.md, README.md, manifests/init.pp, metadata.json, spec/classes/motd_spec.rb
Hello,
I was able to merge everything into a single commit, removed references to versioning and fixed styling issues.
=> Added logic for Windows Logon Message

manifests/init.pp
Bring module to compliance with style guidelines.
=> Removed trailing whitespace, proper spacing. MODULES-2663

CHANGELOG.md, metadata.json
Prep for first Puppet Labs supported release of this module.
=> Changelog and metadata update for 1.4.0 release

README.md
Please check rewritten bits to make sure I didn't change meaning or tell the user to do something silly.
=> FM-4620: edit motd README

README.md
Not sure about version 10 of SLES. Feel free to remove and keep 11 and 12.
=> Corrected SLES version

.rubocop.yml, .travis.yml, Rakefile, appveyor.yml, metadata.json, tests/beaker/tests/01_create_motd_content.rb
pdk version: `1.5.0` 
pdk template ref: `heads/master-0-g34e3266`
=> pdksync - Update using 1.5.0

locales/ja/puppetlabs-motd.po, spec/acceptance/locales_spec.rb, spec/spec_helper_acceptance.rb
i18n test coverage implemented
=> (maint) - Temporary .po created for Japanese translations

.rubocop.yml, .travis.yml, appveyor.yml, metadata.json, spec/default_facts.yml
(FM-7392) puppet 6 testing changes
pdk version: `1.7.0`
=> pdksync - (FM-7392) puppet 6 testing changes

.sync.yml, metadata.json, spec/acceptance/locales_spec.rb, spec/acceptance/motd_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
- SpecInfra Implemented
- Idempotent Apply Method Implemented
- Code Coverage enabled on Unit test's
=> (FM-7799) - Cleanup of MOTD Testing

metadata.json
(maint) Update pdk-template to f778803
pdk version: `1.10.0`
=> pdksync - (maint) Update pdk-template to f778803

.travis.yml
Making the ENV variables align and match.
=> (maint) - More consistent ENV vars for .travis.yml

.rubocop.yml, .vscode/extensions.json, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb
pdksync_heads/master-0-g7827fc2
pdk version: `1.10.0`
=> pdksync - pdksync_heads/master-0-g7827fc2

CHANGELOG.md, metadata.json
Release checks ran successfully
=> (MODULES-9643) Release prep v3.1.0

CHANGELOG.md, metadata.json
=> (MODULES-9647) - Release Merge back v3.1.0

CHANGELOG.md, metadata.json
=> (MODULES-10087) - Release Merge back v4.0.0

metadata.json, provision.yaml
=> (FM-8691) - Addition of Support for CentOS 8

manifests/init.pp
A run of puppet-lint flagged these items.
=> Resolve puppet-lint

CHANGELOG.md, metadata.json
The pr has been created to test through the GCP workflows
=> Release mergeback pr 4.3.0

.github/workflows/nightly.yml, .github/workflows/pr_test.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile, metadata.json
Update gha templates
pdk version: `1.19.0.pre (47)`
=> pdksync - Update gha templates

manifests/init.pp, metadata.json
See:
https://www.freebsd.org/cgi/man.cgi?query=motd&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE
=> Update motd location for FreeBSD 13 and above

.devcontainer/README.md, .sync.yml, Gemfile, metadata.json
pdksync/remove_puppet_module_gems
pdk version: `2.5.0`
=> pdksync - (PDKSync) Removal of puppet_module_gems

metadata.json
CONT-494/pin_github_changelog_generator
pdk version: `2.5.0`
=> pdksync - (CONT-494) PDK Update

.sync.yml, metadata.json, spec/classes/motd_spec.rb, spec/default_facts.yml, spec/spec_helper.rb
Provide a detailed description of all the changes present in this pull request.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (maint) - Add fqdn networking fact to .sync.yml

spec/classes/motd_spec.rb
Update the tests to account for background changes in the test environment
=> (MAINT) Update tests to account for background changes
