puppetlabs/puppetlabs-motd

- README.md
- manifests/init.pp
- metadata.json
- spec/classes/motd_spec.rb
Added option to disable the dynamic motd on Debian based systems, added rspec-puppet tests. Updated readme and added dependancy on stdlib in metadata.json file.
> Added option to disable dynamic motd on Debian based systems

- .fixtures.yml
This PR fixes:
```
.......F..
Failures:
1) motd On Debian based    Operating Systems When dynamic motd is false should contain File_line[dynamic_motd] with line => "session    optional     pam_motd.so  motd=/run/motd.dynamic noupdate"
Failure/ Error: it { should contain_file_line('dynamic_motd').with_line('session    optional     pam_motd.so  motd=/run/motd.dynamic noupdate') }
Puppet::Error:
Puppet::Parser::A    ST::Resource failed with error ArgumentError: Invalid resource type file_line at motd/spec/fixtures/modules/motd/manifests/init.pp:45 on node buildserver
Finished in 0.62725 seconds
110 examples, 1 failure
```
> Add missing stdlib fixture

- Gemfile
- spec/acceptance/motd_spec.rb
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/ubuntu.yml
- spec/spec_helper_acceptance.rb
Once I get a +1 I'll squash the commits according to the contributing guidelines.
> Beaker tests modules 2665

- CHANGELOG.md
- Gemfile
- metadata.json
[MODULES-2845](https://tickets.puppetlabs.com/browse/MODULES-2845)
From `CHANGELOG.md`:
This release adds documentation updates, test improvements, and os support.
- Acceptance testing on Linux platforms
- Rewritten documentation, inclusion of strings for automated documentation.
- Linting of manifest to conform to style guidelines.
- Adds support for several Operating Systems:
- Debian 6, 7
- CentOS 5, 6, 7
- Oracle Linux 6, 7
- Scientific Linux 5, 6, 7
> Cut 1.3.0 release - MODULES-2845

- spec/acceptance/motd_spec.rb
The test to validate dynamic_motd on Debian platforms is unnecessary
because the default for dynamic_motd is true, and the block of code that
modifies the config file is never touched by the module in this usecase.
> (maint) Removes unnecessary test

- README.md
- manifests/init.pp
- spec/acceptance/motd_spec.rb
- spec/classes/motd_spec.rb
Introduces new parameters: issue_template, issue_content, issue_net_template, issue_net_content - to control what if anything is written to /etc/issue and /etc/issue.net respectively.  Includes tests and documentation.
> (#5955) Support for /etc/issue and /etc/issue.net

- manifests/init.pp
Pretty simple.  motd works on Linux the same as Solaris.
> Added Solaris support to motd

- spec/classes/motd_spec.rb
- templates/motd.erb
Improves out-of-the-box useability. Changes default message to include FQDN, Processor, and Kernel in addition to the old messages Operating system and free memory. Removes domain as this is included in FQDN. Removes test to test when domain fact is nil.
> (MODULES-3593) Changes default MOTD to something more useful

- manifests/init.pp
This sets the file mode to 0644, to allow for
non-root users to read the file
> Add set mode for File

- manifests/init.pp
- metadata.json
- spec/classes/motd_spec.rb
MODULES-6599 - Support FreeBSD for puppet module MOTD
> MODULES-6599 - Make MOTD compatible with FreeBSD

- .gitignore
- .rubocop.yml
- .sync.yml
- .travis.yml
- .yardopts
- appveyor.yml
- metadata.json
- spec/spec_helper.rb
The main reason for running this `pdk update` is that the initial convert removed 32 bit testing on appveyor, this PR will enable this again.
> (MODULES-6650) - PDK update 1.4.1

- .sync.yml
- .travis.yml
- manifests/init.pp
- spec/classes/motd_spec.rb
This PR adds support for AIX to specify a `/etc/motd`, `/etc/issue` and `/etc/issue.net`.
> (MODULES-7069) Add compatibility for AIX

- .fixtures.yml
- metadata.json
- spec/spec_helper_acceptance.rb
Bumping puppetlabs-stdlib upper boundary as puppetlabs-stdlib 5.0.0 has been released. 
Removing the pin to registry as it is now on version 2.2.0 and the pinned version was very old. 
Finally removing the install code in `puppetlabs_spec_helper_acceptance.rb` as there is no need to install the registry modules again when it is listed in `.fixtures.yml` and `metadata.json`.
> (maint) removing registry pin, update stdlib bound

- README.md
The parameter is named issue_net_content, not issue__net_content
> Fix parameter name for issue_net_content in README.md

- README.md
Following the documentation currently doesn't work as the `epp` function looks for and then adds the `epp` extension.
> Update documentation to match epp templates

- metadata.json
Currently our internal CI is testing and passing on Oracle5. As we support Oracle 6 and 7 I have also now added Oracle 5 to the OS list.
> (FM-7522) - Updating metadata.json to contain Oracle 5

- README.md
- spec/classes/motd_spec.rb
- templates/motd.epp
As memoryfree is constantly changing, it does not make sense to include it in the template as this results in the file resource being changed during every agent run. I am changing this to memorysize since the other attributes in the template are related to the static hardware configuration of the machine.
> (MODULES-8758) Change memoryfree to memorysize in template

- appveyor.yml
- provision.yaml
Prior to this commit the only provisioners included in
the provision lists were docker and vmpooler, neither
of which are particularly accessible to folks developing
on Windows outside of Puppet.
This commit adds a list which leverages the vagrant
provisioner.
> (FM-8275) Add vagrant provision list

- manifests/init.pp
JIRA issue: MODULES-10336.
FreeBSD does not have a group called 'root' - it is called 'wheel'.
> FreeBSD compatibility

- .github/workflows/nightly.yml
- .github/workflows/pr_test.yml
When running acceptance tests across platforms, usually
we should only be seeing platform-specific failures.
Hence aborting cells due to unrelated failures is
counter productive.
This change configures the jobs to let all matrix cells
run to completion.
> (maint) Don't abort matrix cells because of unrelated failures

- Gemfile
Bolt was formerly pinned to a specific version in order to avoid certain broken versions
> (maint) - Remove Bolt pin

- spec/classes/motd_spec.rb
Prior to this PR spec tests were failing because a change was introduced that used hash map style syntax for retrieving facts.
The existing tests did not cater for this and would cause failures because the requested fact was not defined.
This PR fixes the issue by adding an OS has in to the defined facts for the FreeBSD spec.
> (GH-422) Fix broken spec tests

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
Support for Windows Server 2008 R2 was removed.
Support for FreeBSD was removed.
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Dropped support for Windows Server 2008 R2 and FreeBSD

- .sync.yml
Versions above 1.15.2 seem to suffer from a dependency chain issue where the async gem implicitly sets the minimum supported ruby version to 3.0.
This change ensures that we pin to 1.15.2 in the .sync.yaml.
> (CONT-422) - Pin changelog generator

- metadata.json
Following the last major version update for puppetlabs-registry, several modules found themselves needing a dependency update. This commit aims to adjust the registry dependency within the module so that it is compatible with registry 5.0.0 and onwards.
> (CONT-860) Update registry dependency

- spec/classes/motd_spec.rb
Expected values have changed in the background so the test must be updated to match.
> (BUGFIX) Update values to correctly reflect what is expected

- spec/classes/motd_spec.rb
This module is currently used in oder to test the PDK, with commands being run against it.
As part of this however the values returned by the tests I have updated here can vary between the PDK integration test suite on Jenkins and the MOTD test suite on Github Actions.
This change aims to resolve this by generalizing the expected values that can very between them.
> (CAT-1805) Update tests to account for PDK integration

- spec/classes/motd_spec.rb
This module is used by the PDK as part of its integration testing, the PDK cloning it down and running `pdk test unit` against it. However due to the differences between the machines the tests are run on, the output of this test is slightly different.
> (CAT-2340) Update tests to resolve failures on the PDK package step
